name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f2004343@ds.study.iitm.ac.in
        run: echo "Hello, world! This is Workflow Action Test"
